[project]
name = "stacksbet-arena"
description = "Decentralized Prediction Markets on Stacks"
authors = ["Bamzz"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.stacksbet-arena]
path = "contracts/stacksbet-arena.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
